### ISSUE TITLE
pymaid.graph_utils has become navis.graph_utils

### ISSUE THREAD

**Issue by jasper-tms** [funkelab/synful#1]
As of pymaid2.0 a bunch of neuron morphology tools have been moved out of pymaid and into [navis](https://pypi.org/project/navis/), including the one function you use [here](https://github.com/funkelab/synful/blob/master/synful/synapse.py#L266). So you can drop the import of Philipp's `pymaid` and now you need to `import navis` instead, and use `navis.graph_utils.dist_between` instead of `pymaid.graph_utils.dist_between`. 'pymaid' can be dropped from `requirements.txt` and replaced by `navis`.

(The following bug report won't be relevant after the change above, but synful's `requirements.txt` includes 'pymaid' which looks like it's supposed to refer to Philipp Schlegel's pymaid but is actually getting https://pypi.org/project/pymaid/ By some bad luck, this particular package has some prerequisites that clash with CloudVolume's prerequisites, making synful and CloudVolume unable to be installed in the same environment currently (at least for me). You could change this line in requirements.txt to `python-catmaid` which Philipp recently claimed as the pip install name for his pymaid package ([link](https://pypi.org/project/python-catmaid/)) but again, the change I suggest above means you no longer need this prerequisite at all, you need `navis` instead.)

**Comment by juliabuhmann** [comment]
Cool. Thanks for pointing that out! Pymaid is still required as this is used [elsewhere](https://github.com/funkelab/synful/blob/master/synful/evaluate_annotations.py#L255).

I fixed both issues (replaced pymaid with navis were this was needed, and fixed pymaid --> python-catmaid in requirements.txt)
